FROM node:20-alpine

RUN corepack enable

WORKDIR /app

COPY server/package.json server/pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile --prod

COPY server/. .

ENV NODE_ENV=production
ENV PORT=8787

EXPOSE 8787
CMD ["pnpm", "start"]
